WILLENIUM_TESTRAIL_BASE_URL=
WILLENIUM_TESTRAIL_USERNAME=
WILLENIUM_TESTRAIL_PASSWORD=
WILLENIUM_TESTRAIL_PROJECT_ID=
# Optional for multi-suite TestRail projects
WILLENIUM_TESTRAIL_SUITE_ID=
# Optional display name for created runs
WILLENIUM_TESTRAIL_RUN_NAME=Willenium
# Optional priority for newly created cases
WILLENIUM_TESTRAIL_PRIORITY_ID=3
